name: Automatic Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        run: |
          title="Automatic Pull Request"
          body="This is an automatic pull request created by GitHub Actions."
          head="hub-test"
          base="dev_foley_form" # Change this to the branch you want to create a pull request from

          # Ensure the pull request was merged into the specified base branch
          if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.action }}" = "closed" ] && [ "${{ github.event.pull_request.base.ref }}" = "$base" ]; then
            curl -X POST \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/json" \
              -d "{\"title\":\"$title\",\"body\":\"$body\",\"head\":\"$head\",\"base\":\"$base\"}" \
              "https://api.github.com/repos/${{ github.repository }}/pulls"
          else
            echo "No action needed. Pull request was not merged into the specified base branch."
          fi
