name: Automatic Pull Request

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = "Automatic Pull Request";
            const body = "This is an automatic pull request created by GitHub Actions.";
            const head = "hub-test";
            const base = "dev_foley_form"; # Change this to the branch you want to create a pull request from

            // Ensure the pull request was merged into the specified base branch
            if (github.context.payload.pull_request.merged && github.context.payload.pull_request.base.ref === base) {
              const response = await github.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title,
                body,
                head,
                base,
              });

              console.log(`Pull Request created: ${response.data.html_url}`);
            } else {
              console.log("No action needed. Pull request was not merged into the specified base branch.");
            }
