name: Create PR on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Info
        run: |
          echo "GitHub Event:"
          echo "${{ toJson(github.event) }}"
          echo "Current Branch:"
          git branch
          echo "Git Log:"
          git log --oneline -n 5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Create PR on Merge
        run: |
            gh pr create --base main --head dev_wf_22 --title "Automatically created pull request" --body "data"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
