name: Create PR on Merge

on:
  pull_request:
    branches: [dev_feature_1]
    types: [closed]

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Debug Info
        run: |
          echo "GitHub Event:"
          echo "${{ toJson(github.event) }}"
          echo "Current Branch:"
          git branch
          echo "token-${{ secrets.GH_TOKEN }}"
          echo "secrets-${{ toJson(secrets) }}"
          echo "Git Log:"
          git log --oneline -n 5
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
      - name: Create PR on Merge
        run: |
          gh pr create --base test --head dev_feature_1 --title "Automatically created pull request" --body "data"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
